# Generated by Django 5.1.1 on 2024-09-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
